Del /Q build\temp\Win32
Del /Q build\temp\Win64
Del /Q build\temp\i386
Del /Q build\temp\x86_64
Del /Q rich-demos\i386-bsd\tmp
Del /Q rich-demos\i386-linux\tmp
Del /Q rich-demos\i386-win32\tmp
Del /Q rich-demos\Raspberry\tmp
Del /Q rich-demos\x86_64-linux\tmp
Del /Q rich-demos\x86_64-win64\tmp
Del /Q LabVIEW\lib_tmp\win32
Del /Q LabVIEW\lib_tmp\win64
Del /S *.~*
Del /S *.bak
Del /S *.dcu
Del /S *.ppu
Del /S *.a
Del /S *.d
Del /S *.o
Del /S *.obj
Del /S *.ild
Del /S *.ilk
Del /S *.ilc
Del /S *.#??
Del /S *.lif
Del /S *.map
Del /S *.tds
Del /S *.ncb
Del /S *.pdi
Del /S *.ilf
Del /S *.ils
Del /S *.sdf
Del /S *.pch
Del /S *.pdb
Del /S *.exp
Del /S *.log
Del /S *.tlog
Del /S *.ipch
Del /S *.user